version: '3'
services:
  line-Chatbot:
    container_name: line-Chatbot-Container
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    image: line-chatbot
    ports:
      - "3000:3000"
    # networks:
    #   - ngrok_network
    environment:
      - DATABASE_USER=dockercompose_User
      - DATABASE_PASSWORD=your_DB_password_here  # Modify with your actual DB password
      - LINE_CHANNEL_ACCESS_TOKEN=Pd4BMfqRLQfM5CLN6wZIHS3l99R88YlFPKsUtJDiy+1CdbqNTF0pGc4bPxgqslfYNt4nV839UbEYBtZiK2zXQ8F8VB4dyR+faHCYwrWKACgD3C/31y+pU1nJnNUwAQydysh3bRimvrxh2DCZ6440vAdB04t89/1O/w1cDnyilFU=
      - LINE_CHANNEL_SECRET=9006f76f6617bd3f5dc45348a6fbbf43
   

# ใช้ docker run --net=host -it --name ngrok-Container ngrok/ngrok http 3000 ไปก่อน

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040
