version: '3'
services:
  line-Chatbot:
    container_name: line-Chatbot-Container
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    image: line-chatbot
    ports:
      - "3000:3000"
    # networks:
    #   - ngrok_network
    environment:
      - DATABASE_USER=dockercompose_User
      - DATABASE_PASSWORD=your_DB_password_here  # Modify with your actual DB password
    depends_on: 
      - ngrok


# ใช้ docker run --net=host -it --name ngrok-Container ngrok/ngrok http 3000 ไปก่อน

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
