version: '3'
services:
  line-Chatbot:
    container_name: line-Chatbot-Container
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    image: line-chatbot
    ports:
      - "3000:3000"
    # networks:
    #   - ngrok_network
    environment:
      - DATABASE_USER=dockercompose_User
      - DATABASE_PASSWORD=your_DB_password_here  # Modify with your actual DB password


# ใช้ docker run --net=host -it --name ngrok-Container ngrok/ngrok http 3000 ไปก่อน

  # ngrok:
  #   image: ngrok/ngrok
  #   restart: unless-stopped
  #   # restart: always
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #     # - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - "4040:4040"


  ngrok:
    image: ngrok/ngrok
    command: http 3000
    ports:
      - "4040:4040"

    network_mode: host


# networks:
#   ngrok_network:
#     driver: bridge
