version: '3'
services:
  line-Chatbot:
    container_name: line-Chatbot-Container
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    image: line-chatbot
    ports:
      - "3000:3000"
    # networks:
    #   - ngrok_network
    environment:
      - DATABASE_USER=dockercompose_User
      - DATABASE_PASSWORD=your_DB_password_here  # Modify with your actual DB password
      - LINE_CHANNEL_ACCESS_TOKEN=Un6AZEYZ09e6CcVVX0IuITKtXVZ02gBkXrlULtUvGjIJZXQlmPzeGK6xuWB3l1wyNt4nV839UbEYBtZiK2zXQ8F8VB4dyR+faHCYwrWKACjCw/5060c8QqQx2nI4J7YoeXeKnU9xDW0xeIKJrRCbOAdB04t89/1O/w1cDnyilFU=
      - LINE_CHANNEL_SECRET=9006f76f6617bd3f5dc45348a6fbbf43
  
  # jenkins:
  #   container_name: jenkins-Container
  #   image: jenkins/jenkins
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000"
  #   environment:
  #     # admin password
  #     - JENKINS_ADMIN_PASSWORD=password
